title: Default
sections:
  main:
    display: Main
    fields:
      -
        handle: markdown
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: true
          smartypants: false
          type: markdown
          localizable: false
          display: markdown
