title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: content
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: true
          smartypants: false
          type: markdown
          localizable: false
          display: Content
      -
        handle: price
        field:
          character_limit: 0
          type: text
          localizable: false
          display: Price
          validate: required|numeric
      -
        handle: images
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 0
          type: assets
          localizable: false
          display: Image
